### ISSUE TITLE
Google Reader username gets cut off

### ISSUE THREAD

**Issue by seyfro** [dcramer/wp-lifestream#1]
WordPress: 2.8.2 (Upgrade)
Lifestream Version: 0.99.9.5 DE-Edition
MySQL: 5.0.51a
PHP: 5.2.8

I use my Google Reader shared items (http://www.google.at/reader/shared/harm.robert) for my lifestream - till the mid of November 09 it worked fine, since then (I dont know what changed), I get the following error and feed is not synchronized to my lifestream anymore:

exception \'Lifestream_FeedFetchError\' with message \'Error fetching feed from http://www.google.com/reader/public/atom/user%2Fharm%2Fstate%2Fcom.google%2Fbroadcast (XML error: Empty document at line 1, column 1).... Invalid stream name.\' in [...]

From this message I found that as username only harm is saved in options and not harm.robert (although entered correctly in admin-interface):
a:7:{s:3:"url";s:46:"http://www.google.at/reader/shared/harm.robert";s:7:"user_id";s:4:"harm";s:7:"grouped";N;s:7:"excerpt";s:1:"0";s:10:"feed_label";s:13:"Google Reader";s:8:"icon_url";s:0:"";s:9:"auto_icon";s:1:"1";}

I tried to change this via phpmyadmin directly to harm.robert but it didnt work, it was overwritten by harm.
Please help
thanks

**Comment by dcramer** [comment]
Thanks. The problem was with the pattern checking for the username. Will be fixed in 0.99.9.6

**Comment by MikeMcQuaid** [comment]
I'm getting the same problem.
