### ISSUE TITLE
rawurlencoded URL's break links in youtube events

### ISSUE THREAD

**Issue by futtta** [dcramer/wp-lifestream#12]
the URL's in the events seem to be (raw)urlencoded since a couple of weeks, which means e.g. that clicking a link in a youtube-event results in an error. 

I think this is related to the simplepie-upgrade that got introduced with lifestream 0.99.9.6. (raw)urldecoding before echoing the html should solve this?

**Comment by dcramer** [comment]
Fixed in 0.99.9.7.1 -- wish I would have read this ticket fully sooner, it was def an issue with the simplepie upgrade.

**Comment by futtta** [comment]
thanks! any idea when te new version will be pushed to the wordpress plugin directory? it's still 0.99.9.6 there :-/
