### ISSUE TITLE
Google Reader Shared time

### ISSUE THREAD

**Issue by Sparticuz** [dcramer/wp-lifestream#18]
Need to display the time the article was shared by the user instead of when the article was published by the author.

extensions\googlereader\extension.inc.php
Before line 56: 
$data['date'] = $row->data['attribs']['http://www.google.com/schemas/reader/atom/']['crawl-timestamp-msec']/1000;

This will take the crawl-timestamp-msec (which is the time the article was shared, [in milliseconds]) and divide by 1000 to get it's unix timestamp. For some reason my php kept the decimals, but when I tried to (int) it, it was a bogus response.

**Comment by Sparticuz** [comment]
btw, it worked with the decimals. it also stored with the decimals in mysql, but it displayed the proper time :-)

**Comment by dcramer** [comment]
Fixed in 0.99.9.7.1 thanks!
