### ISSUE TITLE
small css change for icons

### ISSUE THREAD

**Issue by seyfro** [dcramer/wp-lifestream#2]
When watching my lifestream on my iphone (www.ihrwebprofi.at), the lifestream_icons are displayed in the middle instead of top left due to the small with of the screen. 

I would prefer if you´d change this in themes/main.inc.php on line 35 to <td class="lifestream_icon" valign="top"> respectively change the lifestream_icon class in the css-file.

**Comment by Sparticuz** [comment]
because this is a change to a theme file, all you need to do is copy the theme to a different folder, then set that theme as your default. that way whenever lifestream is upgraded it won't over-write your current theme
