### ISSUE TITLE
add_rewrite_tag Always Returned

### ISSUE THREAD

**Issue by s1n** [dcramer/wp-lifestream#21]
I cloned this repo into my plugin folder, fixed the permissions, and tried activating the plugin. Upon doing so, I get the following error returned to all of my Wordpress pages:

Fatal error: Call to a member function add_rewrite_tag() on a non-object in /path/to/blog/wp-includes/post.php on line 845

Wordpress: 3.0alpha (I know, it's bleeding)
New Install
Lifestream Git checksum: dbeed362016651c521307e47ddd9c85c5c9c47b1
MySQL: 5.0.84-r1
PHP: 5.2.12

**Comment by kodi** [comment]
3 months and no answer? :(

**Comment by dcramer** [comment]
Sorry for the late reply (been super busy). This is now fixed in master.
