### ISSUE TITLE
preg_replace_callback Misuse

### ISSUE THREAD

**Issue by s1n** [dcramer/wp-lifestream#22]
I added a feed for Identi.ca and when I had @user replies, I would get the following error:

 Warning: htmlspecialchars() expects parameter 1 to be string, array given in /path/to/blog/wp-content/plugins/lifestream/extensions/identica/extension.inc.php on line 25

I looked into the matter and it looks like preg_replace_callback on line 30 of extensions/identi.ca/extension.inc.php is not used correctly. On line 25, the only parameter, $user, is being treated as a scalar, when it is actually an array as per the documentation:

http://php.net/manual/en/function.preg-replace-callback.php

I was able to fix it by changing line 25 to be the following:

```
return $this->lifestream->get_anchor_html('@'.htmlspecialchars($user[2]), $this->get_user_url($user[2]), array('class'=>'user'));
```

I used $user[2] because according to the documentation of preg_replace_callback, the first index is the complete match and rest are the captures, so this is the second capture (though I'm not sure what the first capture would be).

Wordpress: 3.0alpha (I know, it's bleeding)
New Install
Lifestream Git checksum: dbeed36 (also for 0.99.9.6)
MySQL: 5.0.84-r1
PHP: 5.2.1

**Comment by dcramer** [comment]
Just pushed a fix for this. Seems this was overlooked when separating it from Twitter.
