### ISSUE TITLE
feature request: option to disable time for entries

### ISSUE THREAD

**Issue by seyfro** [dcramer/wp-lifestream#3]
Hi David,
one thing I miss in wp-lifestream: the option within admin-panel to hide the time of entries. With every update I have to do this manually: 
themes/defaul/main.inc.php:

Hope, this feature could make it into the next release.
Regards,
Robert

**Comment by Sparticuz** [comment]
you could always copy the default theme to another folder and change that line, that way when you update it won't be overwritten. Because this is just an edit to a theme file it probably won't be included.

**Comment by BrookeDot** [comment]
You should also be able to do this by using jquery. Just call Jquery into your template and add this line to your scripts "$('.lifestream_hour').remove();"
