### ISSUE TITLE
Twenty Ten Theme Problems

### ISSUE THREAD

**Issue by haraldpdl** [dcramer/wp-lifestream#34]
WordPress 3.0
Lifestream 0.99.9.8 (Github)

Following problems exist with the default TwentyTen theme:
- Entries not separated by dates
- Right side widgets are pushed at the bottom of the page (Primary Widget Area)

This can be seen here:

http://www.shinyredapples.com

Tested with Chrome/Firefox/Safari on Mac. Did not experience this with 0.99.9.6.

**Comment by haraldpdl** [comment]
Possible fix for the widgets being pushed to the bottom of the page:

SHA: c8ddc264ca5295cae13b4dfade8d8ff4da887c8b

**Comment by tonyduckles** [comment]
FYI, I was able to fix this by editing lifestream/templates/home.php and event.php by changing the top 

<pre>
  &lt;div id="content" class="narrowcolumn" role="main"&gt;
</pre>

...to:

<pre>
 &lt;div id="container"&gt;
   &lt;div id="content" role="main"&gt;
</pre>


...and adding an extra closing "&lt;/div&gt;" at the end of each template.
