### ISSUE TITLE
Twitter should not use cleartext passwords

### ISSUE THREAD

**Issue by s1n** [dcramer/wp-lifestream#37]
When using the twitter feed, it needs a password, which it passes in cleartext. This is a security concern and is not even necessary. Twitter provides an RSS feed. The format is: 

http://twitter.com/statuses/user_timeline/USERID.rss

The module should function without needing a password or providing it in cleartext.

**Comment by dcramer** [comment]
The password is not required unless your feed is private.

**Comment by s1n** [comment]
My mistake. I must have misread the warning. I tried it and it does indeed work.
