### ISSUE TITLE
Invalid RSS feed

### ISSUE THREAD

**Issue by seyfro** [dcramer/wp-lifestream#4]
## I wanted to make my own iphone app with appmakr.com and got the following error from the support team:

Hi Robert,
## Your first feed http://www.ihrwebprofi.at/feed/lifestream-feed is not validating and is trapping the application. Can you fix the feed and resubmit the application?

When you check the feed at http://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fwww.ihrwebprofi.at%2Ffeed%2Flifestream-feed you get the following errors:

This feed does not validate.
- line 2, column 0: XML parsing error: <unknown>:2:0: XML or text declaration not at start of entity [help]
  <?xml version="1.0" encoding="UTF-8"?>
  In addition, interoperability with the widest range of feed readers could be improved by implementing the following recommendations.
- Feeds should not be served with the "text/html" media type [help]
- Your feed appears to be encoded as "utf-8", but your server is reporting "US-ASCII" [help]

Problem with this invalid rss feed is, that also the very common facebook application "networkedblogs" is not syncing the feeds to the facebook wall.

**Comment by seyfro** [comment]
With v0.9.9.6, this problem is solved

**Comment by dcramer** [comment]
Thanks
