### ISSUE TITLE
Twitter OAUTH

### ISSUE THREAD

**Issue by teckie** [dcramer/wp-lifestream#42]
Twitter feed can't be retrieved starting September 1, 2010. I think it's because they changed to OAUTH instead of the basic one.

WP: Version 3.0.1
Lifestream: Version 0.99.9.8-BETA

**Comment by Vlahn** [comment]
I'll second this. Basic authentication is now dead, as outlined here (http://dev.twitter.com/announcements). Are their any plans to update the lifestream plugin to use oAuth for user-authentication? 
While I CAN add my Twitter RSS as a generic feed, lifestream turns the entire content of each status update into a link to the individual status update page at twitter.com, meaning links within the text of each update no-longer work directly from a blog page.

**Comment by ronaldlokers** [comment]
Can this please be updated to use oAuth?

**Comment by simonnreynolds** [comment]
this is definitely an issue that needs to be looked up.. should be easy to fix

**Comment by mousey** [comment]
I've fixed this issue:

<a href='http://www.robmcghee.com/programming/twitter-for-lifestream-fix/'>http://www.robmcghee.com/programming/twitter-for-lifestream-fix/
</a>

You just add: 
<code> .'&source=twitterandroid' </code>

After the end of line 72:
<code>return $url_base . '/statuses/user_timeline/'.$this->get_option('username').'.rss?page='.$page.'&count='.$count; 
</code>

Giving you this:
<code>return $url_base . '/statuses/user_timeline/'.$this->get_option('username').'.rss?page='.$page.'&count='.$count.'&source=twitterandroid';</code>

You can see that it's worked on my blog at <a href='http://robertmcghee.co.uk'>http://robertmcghee.co.uk</a>

**Comment by tquizzle** [comment]
@mousey - Doesnt seem to work for me. I've noticed that the requested change has been added to the master here, but none of my Twitter feeds are updating nor can I add a new one.
When adding new one this is what I get:

There were errors with your request:

Error fetching feed from http://twitter.com/statuses/user_timeline/[myusername].rss?page=1&count=20&source=twitterandroid (A feed could not be found at )....
<?xml version="1.0" encoding="UTF-8"?>
<hash>
<request>/statuses/user_timeline[myusername].rss?page=1&amp;count=20&amp;source=twitterandroid</request>

The funny, or annoying part of this is that I can click the link and clearly see the atom feed with all its details. So why is lifestream unable to account for this feed?

**Comment by mousey** [comment]
@tquizzle 

I'm not a programming guru I just found out about the flag sorry. but at a guess I would say it sounds like you have a non UTF-8 characters in your current 20 tweets and so this is causing the script to error.

Other than that sorry I have no idea

**Comment by hm2k** [comment]
@mousey that works for me

Any fix is better than no fix...

**Comment by mousey** [comment]
See above

**Comment by hm2k** [comment]
I saw.

The fix should be implemented.
