### ISSUE TITLE
Youtube changed feed urls

### ISSUE THREAD

**Issue by markphilpot** [dcramer/wp-lifestream#48]
It looks like youtube changed it's urls... It's now: 

http://gdata.youtube.com/feeds/base/users/[user]/favorites
http://gdata.youtube.com/feeds/base/users/[user]/uploads

Also line 65 in extension.inc.php I had to comment out 

$data['player_url'] = $enclosure->get_link();

The apache error was

PHP Fatal error:  Call to a member function get_link() on a non-object

**Comment by Rataxes** [comment]
Thanks!

**Comment by mousey** [comment]
GH-61
