### ISSUE TITLE
Twitter Not Working

### ISSUE THREAD

**Issue by TheZach** [dcramer/wp-lifestream#49]
You need to add OAUTH

**Comment by mousey** [comment]
I've fixed this issue:

<a href='http://www.robmcghee.com/programming/twitter-for-lifestream-fix/'>http://www.robmcghee.com/programming/twitter-for-lifestream-fix/
</a>

You just add: 
<code> .'&source=twitterandroid' </code>

After the end of line 72:
<code>return $url_base . '/statuses/user_timeline/'.$this->get_option('username').'.rss?page='.$page.'&count='.$count; 
</code>

Giving you this:
<code>return $url_base . '/statuses/user_timeline/'.$this->get_option('username').'.rss?page='.$page.'&count='.$count.'&source=twitterandroid';</code>

You can see that it's worked on my blog at <a href='http://robertmcghee.co.uk'>http://robertmcghee.co.uk</a>

**Comment by mousey** [comment]
See above
