### ISSUE TITLE
Forum Down

### ISSUE THREAD

**Issue by BeauGiles** [dcramer/wp-lifestream#57]
The Lifestream forums have been down for some time (forums.lifestrm.com/index.php)
There were some handy code excerpts, such as primitive search functionality and a fix for the timezone issue.
I was wondering if the forums will ever return?

**Comment by hm2k** [comment]
/wp-admin/admin.php?page=lifestream-forums.php

This points to the forums in an Iframe which simply says:

The web page at http://forums.lifestrm.com/index.php might be temporarily down or it may have moved permanently to a new web address.

http://www.enthropia.com/labs/wp-lifestream/

This points to: http://www.enthropia.com/labs/forums/

This is also down...

**Comment by skyfaller** [comment]
If the old forums are never returning, could we at least declare a new official forum and link to it in the updated version of the plugin? It's sad having a broken link there.

**Comment by mousey** [comment]
I will look at ammending it this evening. I suggest that we just point it here?

**Comment by mousey** [comment]
Updated the code
