### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by hm2k** [dcramer/wp-lifestream#59]
http://www.enthropia.com/labs/wp-lifestream/

The "View Live Demo" link points here: http://www.davidcramer.net/lifestream

This redirects you to http://justcramer.com/

Can we see a working live demo?

Thanks.

**Comment by mousey** [comment]
You can take a look at my site if you want an example:

http://robertmcghee.co.uk which posts daily digests
http://robertmcghee.co.uk/lifestream-live/ which is the live stream

**Comment by hm2k** [comment]
Thanks.

I got mine working here: http://www.hm2k.com/lifestream

Still, the website(s) should be fixed...
