### ISSUE TITLE
Updated Wordpress Plugin

### ISSUE THREAD

**Issue by mousey** [dcramer/wp-lifestream#67]
I've Added an Updated Wordpress Plugin to the Wordpress Codex Pages

http://wordpress.org/extend/plugins/lifestream-update/

It's a snapshot of the GitHub code and I will update the plugin as new plugins/fixes are added to the code

**Comment by Ramoonus** [comment]
I was about to  do the same under the name: Lifestream Reloaded
maybe we can colaborate?

**Comment by mousey** [comment]
I've been granted access to the original plugins subversion repository so will be able to update that

**Comment by Ramoonus** [comment]
do you have my contact information?

**Comment by entropicamente** [comment]
The old plugin (http://wordpress.org/extend/plugins/lifestream/) will be discontinued?

**Comment by Ramoonus** [comment]
the old plugin readme points to this site?

**Comment by entropicamente** [comment]
I was talking about the plugin directory on wordpress.org.
Now there are 2 identical plugins showing the same name and updated at the same time, but one is lifestream and the other lifestream-update.
I think that it is confusing and that would be easier, for the developer and for the users, to keep only one of them, so i was asking if mousey is planning to stop updating the one that is installed on my blog...

**Comment by Ramoonus** [comment]
i prefer the original lifestream name

**Comment by mousey** [comment]
I will find out how to remove a plugin from the wordpress plugin directory and remove lifestream-update

**Comment by Ramoonus** [comment]
empty the subversion content?
