### ISSUE TITLE
Twitter Problem

### ISSUE THREAD

**Issue by kjgrulle** [dcramer/wp-lifestream#68]
Hey,
check your fix with:
        return $url_base . '/statuses/user_timeline/'.$this->get_option('username').'.rss?page='.$page.'&count='.$count.'&source=twitterandroid';

but it doesn't seem to work anymore.
Got the error:

Error fetching feed from http://schimpy:passworddeleted@twitter.com/statuses/user_timeline/schimpy.rss?page=1&count=20&source=twitterandroid (A feed could not be found at )....

<?xml version="1.0" encoding="UTF-8"?>
<errors>
<error code="53">Basic authentication is not supported</error>
</errors>

Anyone got a fix for this?

**Comment by mousey** [comment]
Try this URL: http://twitter.com/statuses/user_timeline/schimpy.rss?page=1&count=20&source=twitterandroid I get a perfectly legibal RSS stream

**Comment by kjgrulle** [comment]
Yes, me too. But I can't create a feed at lifestream, currently. Do you?
I think the main error is:
Basic authentication is not supported

**Comment by mousey** [comment]
I do have a Twitter Stream and it is working http://robertmcghee.co.uk

In the Twitter extension do not supply a password and see if that corrects this issue

**Comment by paisano** [comment]
I have the same exact problem with twitter

It does not support basic authentication anymore. You have to use the more secure oauth method.

Google plus doesn't work either

**Comment by mousey** [comment]
Updated the extension with current fix
