### ISSUE TITLE
feature request: option to purge old events

### ISSUE THREAD

**Issue by futtta** [dcramer/wp-lifestream#7]
after using lifestream for about half a year, livestream_event and livestream_event_group are approx 2Mb each in size. database size has an important impact on my low-RAM virtual server's performance, so it would be great if there were a setting to automatically purge events/ event_groups that are older then x months.

**Comment by dcramer** [comment]
There is an option in the current version to automatically trim the event log.

**Comment by futtta** [comment]
great you went back in time to add that feature! ;-)

next time i'll go through the options more carefully before requesting new features, promised!
