### ISSUE TITLE
Tumblr extension problem and workaround

### ISSUE THREAD

**Issue by entropicamente** [dcramer/wp-lifestream#74]
Hi, I'm glad seeing that the developement started again.

About a year ago I found a bug in the Tumblr extension. I noticed that the html code created was wrong and i tried to fix it, even if I'm not a php developer.
I found errors in line 66 and 77, changing `Lifestream_TwitterFeed` to `Lifestream_TumblrFeed` solved my issue.

I hope it helps...

**Comment by mousey** [comment]
Made the changes you suggested
