### ISSUE TITLE
Raptr and Wowarmory feeds broken

### ISSUE THREAD

**Issue by Jasun** [dcramer/wp-lifestream#75]
exception \'Lifestream_FeedFetchError\' with message \'Error fetching feed from http://raptr.com/Jasun/rss (XML error: XML_ERR_NAME_REQUIRED at line 8, column 173).... <!DOCTYPE html> <html lang=\"en\" xmlns:og=\"http://ogp.me/ns#\" xmlns:fb=\"http://www

exception \'Lifestream_FeedFetchError\' with message \'Error fetching feed from http://www.wowarmory.com/character-feed.atom?r=Dragonmaw&cn=Jeysen (A feed could not be found at ).... <html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en-us\"> <head

**Comment by sugartoys** [comment]
i get my raptr fix. the wow one i didnt make research.

so this is what i did... 
to fix the Raprt one go to the extensions folder and look up for Raptr. inside edit the extension.inc.php
look around line 32 and change the url of the feed

change it from

return 'http://raptr.com/'

to

return 'http://old.raptr.com/'

that will do it.

for the wow im not sure  bc i dont use it so i didnt make any research.... but look on wow and verified around the new rss feed url and if u find it do the same thing you did with raptr.

i hope it help mate ;)

**Comment by Jasun** [comment]
awesome that fixed raptr thanks alot!

**Comment by Jasun** [comment]
i found a plugin that will do my wowarmory its called warcraft news.. i just don't like adding 10 feeds in 10 widgets..

**Comment by sugartoys** [comment]
first... no problm thats why we r here to help each other ;)

second... AWSOME! yeah i know to many feeds in to many widgets take a lot of space.

thnx for share that WOW plugin ;)
