### ISSUE TITLE
Kiva Stream error.

### ISSUE THREAD

**Issue by contemplicity** [dcramer/wp-lifestream#77]
Ever since August 9th, I have been receiving errors in LifeStream stating "The data could not be converted to UTF-8".  
This error happened both before and after I upgraded to LifeStream 1.0.

The error only occurs with the Kiva stream, occurs on every single data inquiry, and the full error is below:
exception \'Lifestream_FeedFetchError\' with message \'Error fetching feed from http://www.kiva.org/rss/lender/contemplicity (The data could not be converted to UTF-8).... \' in /home/contempl/public_html/home/wp-content/plugins/lifestream/inc/core.php:2

**Comment by cygnoir** [comment]
I receive a different error ...

```There were errors with your request:
Error fetching feed from http://www.kiva.org/rss/lender/cygnoir (XML error: EntityRef: expecting ';' at line 103, column 76)....
<!DOCTYPE html>
<html lang="en" xmlns:og="http://opengraphprotocol.org/schema/" xmlns:fb="http://www.facebook.com/2008/fbml">
<head>

```
```
