### ISSUE TITLE
Google+ feed error

### ISSUE THREAD

**Issue by Cibertek** [dcramer/wp-lifestream#89]
Trying to add the Google+ feed to my lifestream.  http://jp-nelson.com

There were errors with your request:

Error fetching feed from http://plusfeed.appspot.com/100606327377289673411 (XML error: Mismatched tag at line 5, column 8)....

<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>404 Not Found</title>
</head>
<body text=#000000 bgcolor=#ffff

**Comment by netizenxero** [comment]
Well, I found a possible solution.  It looks like there is an app at appspot that does the same thing, but we would have to change the URL for getting the feed to http://highdn-plusfeed.appspot.com/[idnumber].

I am hunting through the code for the entry, but if anyone could offer a hint as to where I will find the entry to change, it would be a great help.

**Comment by mousey** [comment]
Fixed with @netizenxero suggested URL
